# This rule is not used by the project novasphere itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over vm.novasphere.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: novasphere
    app.kubernetes.io/managed-by: kustomize
  name: wukong-admin-role
rules:
- apiGroups:
  - vm.novasphere.dev
  resources:
  - wukongs
  verbs:
  - '*'
- apiGroups:
  - vm.novasphere.dev
  resources:
  - wukongs/status
  verbs:
  - get
